language: python

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/pip

env:
  - IMGAUG_NO_CV2_INSTALLED_CHECK=TRUE

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true
    - os: windows
      python: 2.7
    - os: windows
      python: 3.5
    - os: windows
      python: 3.6
    - os: windows
      python: 3.7

install:
  - pip install .[tests]
  - pip install flake8 flake8-docstrings

script:
  - pytest
  - flake8
